name: Build Portable Linux JAX Wheels

on:
  workflow_dispatch:
    inputs:
      amdgpu_family:
        type: choice
        options:
          - gfx101X-dgpu
          - gfx103X-dgpu
          - gfx110X-all
          - gfx1150
          - gfx1151
          - gfx1152
          - gfx1153
          - gfx120X-all
          - gfx90X-dcgpu
          - gfx94X-dcgpu
          - gfx950-dcgpu
        default: gfx94X-dcgpu
      python_version:
        required: true
        type: string
        default: "3.12"
      release_type:
        type: choice
        description: Type of release to create. All developer-triggered jobs should use "dev"!
        options:
          - dev
          - nightly
          - prerelease
        default: dev
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: choice
        options:
          - v2
          - v3/whl
        default: v2
      s3_staging_subdir:
        description: S3 staging subdirectory, not including the GPU-family
        type: choice
        options:
          - v2-staging
          - v3/whl-staging
        default: v2-staging
      rocm_version:
        description: ROCm version to install
        type: string
      tar_url:
        description: URL to TheRock tarball to build against
        type: string
      cloudfront_url:
        type: choice
        options:
          - https://rocm.devreleases.amd.com/v2
          - https://rocm.prereleases.amd.com/whl
          - https://rocm.nightlies.amd.com/v2
        default: https://rocm.devreleases.amd.com/v2
      cloudfront_staging_url:
        description: CloudFront base URL pointing to staging Python index
        type: choice
        options:
          - https://rocm.devreleases.amd.com/v2-staging
          - https://rocm.prereleases.amd.com/whl-staging
          - https://rocm.nightlies.amd.com/v2-staging
        default: https://rocm.devreleases.amd.com/v2-staging
      jax_ref:
        description: rocm-jax repository ref/branch to check out
        type: string
        default: rocm-jaxlib-v0.8.0
      ref:
        description: "Branch, tag or SHA to checkout. Defaults to the reference or SHA that triggered the workflow."
        type: string
        default: release/therock-7.11

permissions:
  id-token: write
  contents: read

run-name: Release Linux JAX Wheels (${{ inputs.amdgpu_family }}, ${{ inputs.jax_ref }}

jobs:
  release:
    name: Release | ${{ inputs.amdgpu_family }} | jax ${{ inputs.jax_ref }}
    strategy:
      fail-fast: false

    uses: ROCm/TheRock/.github/workflows/build_linux_jax_wheels.yml@release/therock-7.11
    with:
      amdgpu_family: ${{ inputs.amdgpu_family }}
      python_version: "3.12"
      release_type: ${{ inputs.release_type }}
      s3_subdir: ${{ inputs.s3_subdir }}
      s3_staging_subdir: ${{ inputs.s3_staging_subdir }}
      rocm_version: ${{ inputs.rocm_version }}
      tar_url: ${{ inputs.tar_url }}
      repository: "ROCm/TheRock"
      ref: ${{ inputs.ref }}
      cloudfront_url: ${{ inputs.cloudfront_url }}
      cloudfront_staging_url: ${{ inputs.cloudfront_staging_url }}
      jax_ref: ${{ inputs.jax_ref }}
